### ISSUE TITLE
Тестирование приложения

### ISSUE THREAD

**Issue by dasha032** [goodwinuser/GrafistaMobile#1]
провела тестирование web api, основной функционал работает без ошибок, багов не обнаружила. Замечание: при отправке get запроса по адресу /api/SingIn видна пустая белая страница, не смотря на то, что код возврата - 405. Нужно выводить страницу со статус кодами в подобных ситуациях, чтобы не было замешательства.

**Comment by goodwinuser** [comment]
Страницы со статусными кодами добавлены, дизайн конечно никакой, но стало информативнее.
