### ISSUE TITLE
Код ответа 200

### ISSUE THREAD

**Issue by XiennM** [goodwinuser/GrafistaMobile#2]
Код отрабатывает без ошибок, однако хотела бы заметить, что при post запросе по адресу api/SingIn при удачном запросе возвращается код 200, лучше чтобы возвращало 201(Created). Также при post запросе по адресу api/SingUp лучше возвращать код 202(Accepted), а не 200.

**Comment by goodwinuser** [comment]
Коды изменил, спасибо за бдительность.
